name: 📚 Documentation
description: Report an issue related to documentation
labels: [documentation]
title: '[Docs]: '
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation issues, including:

        - Documenting undocumented Components/APIs;
        - Updating external links;
        - Anything else that doesn't require touching the codebase itself.

        If you followed the documentation but things don't work, take some time to consider if it's the documentation or the code that's wrong. In the latter, prefer using the "bug" template.

  - type: input
    id: page-url
    attributes:
      label: Related page
      description: Which page of the documentation is this about?
      placeholder: https://rcl.icapitalnetwork.com/supernova/core/sidebar/
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Kind of issue
      description: What kind of problem are you facing?
      options:
        - Unclear explanations
        - Missing information
        - Broken demonstration
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue description
      description: |
        Let us know what went wrong when you were using this documentation and what we could do to improve it.
      placeholder: |
        I was looking for ... and it appears that ...

  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        You can add screenshots by drag and drop or by copying and pasting them.
    validations:
      required: false
