name: '🐛 (NEW) -  Bug Report'
description: Create a new report for a bug.
title: '🐛 [BUG] - <title>'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: >
        ### Please provide as much detail as you can so we have a better chance of fixing the bug quickly.
        Thanks for your contribution.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
      placeholder: 'I expected to see ...'
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 'Actual behavior'
      description: A clear and concise description of what is happening.
      placeholder: 'I expected to see ...'
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 'Reproduction steps'
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: If applicable, add screenshots to help explain your problem.
      value: |
        You can add screenshots by drag and drop or by copying and pasting them.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 'Logs'
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: 'Browsers'
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: 'OS'
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
